const StatisticsTypes = {
  CLEAR_STATISTIC_STATE: 'CLEAR_STATISTIC_STATE',

  GET_SALE: 'GET_SALE',
  GET_SALE_BY_YEAR: 'GET_SALE_BY_YEAR',

  TEACHER_GET_STATISTICS: 'TEACHER_GET_STATISTICS',
  TEACHER_GET_STATISTICS_SUCCESS: 'TEACHER_GET_STATISTICS_SUCCESS',
  TEACHER_GET_STATISTICS_FAILURE: 'TEACHER_GET_STATISTICS_FAILURE',
}
export default StatisticsTypes
