const TagType = {
  GET_ALL_TAG: 'GET_ALL_TAG',
  GET_ALL_SUCCESS_TAG: 'GET_ALL_SUCCESS_TAG',
  GET_ALL_FAILURE_TAG: 'GET_ALL_FAILURE_TAG',

  CREATE_TAG: 'CREATE_TAG',
  CREATE_SUCCESS_TAG: 'CREATE_SUCCESS_TAG',
  CREATE_FAILURE_TAG: 'CREATE_FAILURE_TAG',

  EDIT_TAG: 'EDIT_TAG',
  EDIT_SUCCESS_TAG: 'EDIT_SUCCESS_TAG',
  EDIT_FAILURE_TAG: 'EDIT_FAILURE_TAG',

  DELETE_TAG: 'DELETE_TAG',
  DELETE_SUCCESS_TAG: 'DELETE_SUCCESS_TAG',
  DELETE_FAILURE_TAG: 'DELETE_FAILURE_TAG',
}
export default TagType
