const MajorType = {
  GET_ALL_MAJOR: 'GET_ALL_MAJOR',
  GET_ALL_SUCCESS_MAJOR: 'GET_ALL_SUCCESS_MAJOR',
  GET_ALL_FAILURE_MAJOR: 'GET_ALL_FAILURE_MAJOR',

  CREATE_MAJOR: 'CREATE_MAJOR',
  CREATE_SUCCESS_MAJOR: 'CREATE_SUCCESS_MAJOR',
  CREATE_FAILURE_MAJOR: 'CREATE_FAILURE_MAJOR',

  EDIT: 'EDIT_MAJOR',
  EDIT_SUCCESS_MAJOR: 'EDIT_SUCCESS_MAJOR',
  EDIT_FAILURE_MAJOR: 'EDIT_FAILURE_MAJOR',

  DELETE_MAJOR: 'DELETE_MAJOR',
  DELETE_SUCCESS_MAJOR: 'DELETE_SUCCESS_MAJOR',
  DELETE_FAILURE_MAJOR: 'DELETE_FAILURE_MAJOR',
}
export default MajorType
