const UserTypes = {
  LOG_OUT: 'LOG_OUT',

  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  CLEAR_CREATE_ACCOUNT: 'CLEAR_CREATE_ACCOUNT',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  CREATE_ACCOUNT_SUCCESS: 'CREATE_ACCOUNT_SUCCESS',
  CREATE_ACCOUNT_FAILURE: 'CREATE_ACCOUNT_FAILURE',

  GET_ALL: 'GET_ALL_ADMIN_ACCOUNT',
  GET_ALL_SUCCESS: 'GET_ALL_SUCCESS_ADMIN_ACCOUNT',
  GET_ALL_FAILURE: 'GET_ALL_FAILURE_ADMIN_ACCOUNT',

  GET_ALL_USER: 'GET_ALL_USER',
  GET_ALL_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
  GET_ALL_USER_FAILURE: 'GET_ALL_USER_FAILURE',

  GET_ALL_STUDENT: 'GET_ALL_STUDENT',
  GET_ALL_STUDENT_SUCCESS: 'GET_ALL_STUDENT_SUCCESS',
  GET_ALL_STUDENT_FAILURE: 'GET_ALL_STUDENT_FAILURE',

  GET_ALL_TEACHER: 'GET_ALL_TEACHER',
  GET_ALL_TEACHER_SUCCESS: 'GET_ALL_TEACHER_SUCCESS',
  GET_ALL_TEACHER_FAILURE: 'GET_ALL_TEACHER_FAILURE',

  GET_INFOR_USER: 'GET_INFOR_USER',
  GET_INFOR_USER_SUCCESS: 'GET_INFOR_USER_SUCCESS',
  GET_INFOR_USER_FAILURE: 'GET_INFOR_USER_FAILURE',

  BLOCK_UNBLOCK_ACCOUNT: 'BLOCK_UNBLOCK_ACCOUNT',
  BLOCK_UNBLOCK_ACCOUNT_SUCCESS: 'BLOCK_UNBLOCK_ACCOUNT_SUCCESS',
  BLOCK_UNBLOCK_ACCOUNT_FAILURE: 'BLOCK_UNBLOCK_ACCOUNT_FAILURE',
}

export default UserTypes
